name: Lock down PRs
on:
  pull_request:
    types: opened
jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2.0.0
        with:
          github-token: ${{ github.token }}
